version: '3'
services:
  dryeye_defender_service:
    image: dryeye_defender_image
    stdin_open: true # docker run -i
    tty: true
    build:
      context: .
      args:
        GROUP_ID: 1000
        USER_ID: 1000
    environment:
      USERNAME: user
      DISPLAY:
      QT_X11_NO_MITSHM: 1
      TZ: ${TZ}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/.Xauthority:rw
      - .:/mount/
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video3
    working_dir: /mount/
    command: >
      bash -c "python -m dryeye_defender"
    privileged: true
