[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "eyeblink_gui"
version = "1.0"
description = "Eyeblink detection software"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy==1.23.4",
    "opencv-python==4.2.0.32",
    "openvino==2022.3.0",
    "Pillow==9.5.0",
    "PySide6==6.4.2",
    "PySide6-Addons==6.4.2",
    "PySide6-Essentials==6.4.2",
    "shiboken6==6.4.2 ",
]