# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build application for macos

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Checkout submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{secrets.ACCESS_TOKEN}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx-freeze
        pip install -r requirements_mac.txt
        pip install -r submodules/eyeblink-detection/requirements.txt

    - name: build 
      run: |
        python3 setup.py build
        ls
        ls build/
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows_build
        path: build/
